AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    bridge

    Sample SAM Template for bridge

Mappings:
    NetworkMapping:
        "testnet": "AMI-asdasdas"
        "mainnet": "AMI-mainnet"

Parameters: 
  PaymentNodeType: 
    Type: String
    Default: testnet
    AllowedValues: 
      - testnet
      - mainnet
    Description: Enter testnet to deploy with testnet infra or mainnet for the mainnet. Default is testnet.
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 6

Resources:

    CreateOrderFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: bridge/build/
            Handler: app.create_order
            Runtime: python3.6
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    MIN_PURCHASE_AMOUNT: 10
                    CURRENCY_PAIR: XXMRZUSD
                    ORDER_TABLE_NAME: !Ref OrderTable
                    SSH_KEY_BUCKET_NAME: hedgenetkeys
                    SSH_KEY_OBJECT: hedgenet-admin.pem
                    DAEMON_HOST: ec2-35-182-141-65.ca-central-1.compute.amazonaws.com
                    DAEMON_USERNAME: ubuntu
                    DAEMON_PORT: 28888
                    ORDER_ACCOUNT_INDEX: 0

            Events:
                CreateOrderEvent:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /order
                        Method: post

    GetOrderFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: bridge/build/
            Handler: app.get_order
            Runtime: python3.6
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    ORDER_TABLE_NAME: !Ref OrderTable
            Events:
                GetOrderEvent:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /order
                        Method: get

    OrderTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: order
            PrimaryKey:
                Name: order_id
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

Outputs:

    BridgeApi:
      Description: "API Gateway endpoint URL"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
